### ISSUE TITLE
Arch App Youppers

### ISSUE THREAD

**Issue by LeoLeonardo** [youppers/wishlist#10]
In vista di una utenza di progettisti, potrebbe essere interessante che il singolo possa creare dei progetti/case dove poi trovare i singoli ambienti, già esistenti per la lista preferiti.
In soldoni, se io sono un architetto, potrebbe essere che voglio crearmi nel APP, es.:  Casa Strampelli, Casa Carrus, Casa Del Re, dove al loro interno trovo le liste degli ambienti con i prodotti da me ipotizzati nei progetti relativi.
Inoltre dovrebbe essere possibile cancellare ed implementare altri progetti/case, come del resto anche gli eventuali nuovi ambienti creati, da parte del singolo utente direttamente dal proprio APP.

**Comment by rafdelre** [comment]
Si questo mi piace

**Comment by LeoLeonardo** [comment]
ieri mi sembra stavate parlando di questo tu e Sergio, se si, puoi riassumermi quanto emerso?

**Comment by sergiostrampelli** [comment]
Non sono concetti nuovi. Si tratta solo di adoperare profili e sessioni, che ora sono usate solo in parte. Per la struttura è quella delle slide a della architettura che abbiamo visto insieme.

**Comment by LeoLeonardo** [comment]
Ok gazie
