### ISSUE TITLE
opzioni lista preferiti

### ISSUE THREAD

**Issue by LeoLeonardo** [youppers/wishlist#11]
Nella lista preferiti, posso soltanto inserire e non implementare se non dal QR scansito.
Quando si va a consultare la lista preferiti, credo sia carino poter avere 2 cuori, uno pieno (rimuovere dalla lista) e uno vuoto (aggiungere alla lista).
Questo perchè, in caso di implementazione di un prodotto a posteriori mentre consulto la mia lista e/o quella scansionata, potrei ricordarmi di aggiungere un medesimo prodotto anche in altri ambienti.

**Comment by rafdelre** [comment]
Leo cone ti ho fatto vedere, e' gia previsto e funziona con un cuore
Grazie
