### ISSUE TITLE
visibilità proprietà variante

### ISSUE THREAD

**Issue by pinovinci** [youppers/wishlist#8]
Quando si inseriscono le proprietà di una variante, queste vengono visualizzate nell'app sulla schermata "scan result" rispettando quanto caricato nel front end.
Passando alla schermata successiva "options", mi aspetterei di trovare maggiori dettagli, non solo la possibilità di selezionare altri prodotti e docs. Questo è vero solo parzialmente, perché per esempio le proprietà della variante si limitano a quelle decise "a priori" tralasciando quelle eventualmente presenti ma non rientranti nella lista predefinita.

**Comment by sergiostrampelli** [comment]
E' un bug dell'app:
https://github.com/youppers/app/issues/56
